package by.daryazalevskaya.finalproject.dao;

public enum DaoType {
    CONTACT,
    COUNTRY,
    EMPLOYEE,
    EMPLOYEE_PERSONAL_INFO,
    EMPLOYER,
    JOB_PREFERENCE,
    RESUME,
    USER,
    EMPLOYEE_LANGUAGE,
    VACANCY,
    COMPLICATED_RESUME,
    COMPLICATED_EMPLOYER,
    COMPLICATED_VACANCY,
    USER_ACCOUNT;
}
