INSERT INTO contact (id, telephone, email, skype)
VALUES (1, '+375295395676', 'parrot@gmail.com', 'parrot'),
       (2, '+74956789898', 'qwerty@outlook.com', 'pikachi34'),
       (3, '+375295989090', 'qwerty@gmail.com', 'login1456');

INSERT INTO usr(id, role, username, password)
VALUES (1, 'EMPLOYEE', 'pokemon', '01234567890123456789'),
       (2, 'EMPLOYEE', 'Parrot', '0a234cccbb1234567aa'),
       (3, 'EMPLOYER', 'Dasha', '01234567890123456789');





INSERT INTO country (id, name) VALUES (0, 'Russia');
INSERT INTO country (id, name) VALUES (1, 'Ukraine');
INSERT INTO country (id, name) VALUES (2, 'Abkhazia');
INSERT INTO country (id, name) VALUES (3, 'Australia');
INSERT INTO country (id, name) VALUES (4, 'Austria');
INSERT INTO country (id, name) VALUES (5, 'Azerbaijan');
INSERT INTO country (id, name) VALUES (6, 'Albania');
INSERT INTO country (id, name) VALUES (7, 'Algeria');
INSERT INTO country (id, name) VALUES (8, 'Angola');
INSERT INTO country (id, name) VALUES (9, 'Anguilla');
INSERT INTO country (id, name) VALUES (10, 'Andorra');
INSERT INTO country (id, name) VALUES (11, 'Antigua and Barbuda');
INSERT INTO country (id, name) VALUES (12, 'Antilles');
INSERT INTO country (id, name) VALUES (13, 'Argentina');
INSERT INTO country (id, name) VALUES (14, 'Armenia');
INSERT INTO country (id, name) VALUES (15, 'Arulco');
INSERT INTO country (id, name) VALUES (16, 'Afghanistan');
INSERT INTO country (id, name) VALUES (17, 'Bahamas');
INSERT INTO country (id, name) VALUES (18, 'Bangladesh');
INSERT INTO country (id, name) VALUES (19, 'Barbados');
INSERT INTO country (id, name) VALUES (20, 'Bahrain');
INSERT INTO country (id, name) VALUES (21, 'Belarus');
INSERT INTO country (id, name) VALUES (22, 'Belize');
INSERT INTO country (id, name) VALUES (23, 'Belgium');
INSERT INTO country (id, name) VALUES (24, 'Benin');
INSERT INTO country (id, name) VALUES (25, 'Bermuda');
INSERT INTO country (id, name) VALUES (26, 'Bulgaria');
INSERT INTO country (id, name) VALUES (27, 'Bolivia');
INSERT INTO country (id, name) VALUES (28, 'Bosnia / Herzegovina');
INSERT INTO country (id, name) VALUES (29, 'Botswana');
INSERT INTO country (id, name) VALUES (30, 'Brazil');
INSERT INTO country (id, name) VALUES (31, 'British Virgin Islands');
INSERT INTO country (id, name) VALUES (32, 'Brunei');
INSERT INTO country (id, name) VALUES (33, 'Burkina Faso');
INSERT INTO country (id, name) VALUES (34, 'Burundi');
INSERT INTO country (id, name) VALUES (35, 'Bhutan');
INSERT INTO country (id, name) VALUES (36, 'Wallis and Futuna Islands');
INSERT INTO country (id, name) VALUES (37, 'Vanuatu');
INSERT INTO country (id, name) VALUES (38, 'UK');
INSERT INTO country (id, name) VALUES (39, 'Hungary');
INSERT INTO country (id, name) VALUES (40, 'Venezuela');
INSERT INTO country (id, name) VALUES (41, 'East Timor');
INSERT INTO country (id, name) VALUES (42, 'Vietnam');
INSERT INTO country (id, name) VALUES (43, 'Gabon');
INSERT INTO country (id, name) VALUES (44, 'Haiti');
INSERT INTO country (id, name) VALUES (45, 'Guyana');
INSERT INTO country (id, name) VALUES (46, 'Gambia');
INSERT INTO country (id, name) VALUES (47, 'Ghana');
INSERT INTO country (id, name) VALUES (48, 'Guadeloupe');
INSERT INTO country (id, name) VALUES (49, 'Guatemala');
INSERT INTO country (id, name) VALUES (50, 'Guinea');
INSERT INTO country (id, name) VALUES (51, 'Guinea-Bissau');
INSERT INTO country (id, name) VALUES (52, 'Germany');
INSERT INTO country (id, name) VALUES (53, 'Guernsey Island');
INSERT INTO country (id, name) VALUES (54, 'Gibraltar');
INSERT INTO country (id, name) VALUES (55, 'Honduras');
INSERT INTO country (id, name) VALUES (56, 'Hong Kong');
INSERT INTO country (id, name) VALUES (57, 'Grenada');
INSERT INTO country (id, name) VALUES (58, 'Greenland');
INSERT INTO country (id, name) VALUES (59, 'Greece');
INSERT INTO country (id, name) VALUES (60, 'Georgia');
INSERT INTO country (id, name) VALUES (61, 'Denmark');
INSERT INTO country (id, name) VALUES (62, 'Jersey Island');
INSERT INTO country (id, name) VALUES (63, 'Djibouti');
INSERT INTO country (id, name) VALUES (64, 'Dominican Republic');
INSERT INTO country (id, name) VALUES (65, 'Egypt');
INSERT INTO country (id, name) VALUES (66, 'Zambia');
INSERT INTO country (id, name) VALUES (67, 'Western Sahara');
INSERT INTO country (id, name) VALUES (68, 'Zimbabwe');
INSERT INTO country (id, name) VALUES (69, 'Israel');
INSERT INTO country (id, name) VALUES (70, 'India');
INSERT INTO country (id, name) VALUES (71, 'Indonesia');
INSERT INTO country (id, name) VALUES (72, 'Jordan');
INSERT INTO country (id, name) VALUES (73, 'Iraq');
INSERT INTO country (id, name) VALUES (74, 'Iran');
INSERT INTO country (id, name) VALUES (75, 'Ireland');
INSERT INTO country (id, name) VALUES (76, 'Iceland');
INSERT INTO country (id, name) VALUES (77, 'Spain');
INSERT INTO country (id, name) VALUES (78, 'Italy');
INSERT INTO country (id, name) VALUES (79, 'Yemen');
INSERT INTO country (id, name) VALUES (80, 'Cape Verde');
INSERT INTO country (id, name) VALUES (81, 'Kazakhstan');
INSERT INTO country (id, name) VALUES (82, 'Cambodia');
INSERT INTO country (id, name) VALUES (83, 'Cameroon');
INSERT INTO country (id, name) VALUES (84, 'Canada');
INSERT INTO country (id, name) VALUES (85, 'Qatar');
INSERT INTO country (id, name) VALUES (86, 'Kenya');
INSERT INTO country (id, name) VALUES (87, 'Cyprus');
INSERT INTO country (id, name) VALUES (88, 'Kiribati');
INSERT INTO country (id, name) VALUES (89, 'China');
INSERT INTO country (id, name) VALUES (90, 'Colombia');
INSERT INTO country (id, name) VALUES (91, 'Comoros');
INSERT INTO country (id, name) VALUES (92, 'Congo (Brazzaville)');
INSERT INTO country (id, name) VALUES (93, 'Congo (Kinshasa)');
INSERT INTO country (id, name) VALUES (94, 'Costa Rica');
INSERT INTO country (id, name) VALUES (95, 'Cote d Ivoire');
INSERT INTO country (id, name) VALUES (96, 'Cuba');
INSERT INTO country (id, name) VALUES (97, 'Kuwait');
INSERT INTO country (id, name) VALUES (98, 'Cook Islands');
INSERT INTO country (id, name) VALUES (99, 'Kyrgyzstan');
INSERT INTO country (id, name) VALUES (100, 'Laos');
INSERT INTO country (id, name) VALUES (101, 'Latvia');
INSERT INTO country (id, name) VALUES (102, 'Lesotho');
INSERT INTO country (id, name) VALUES (103, 'Liberia');
INSERT INTO country (id, name) VALUES (104, 'Lebanon');
INSERT INTO country (id, name) VALUES (105, 'Libya');
INSERT INTO country (id, name) VALUES (106, 'Lithuania');
INSERT INTO country (id, name) VALUES (107, 'Liechtenstein');
INSERT INTO country (id, name) VALUES (108, 'Luxembourg');
INSERT INTO country (id, name) VALUES (109, 'Mauritius');
INSERT INTO country (id, name) VALUES (110, 'Mauritania');
INSERT INTO country (id, name) VALUES (111, 'Madagascar');
INSERT INTO country (id, name) VALUES (112, 'Macedonia');
INSERT INTO country (id, name) VALUES (113, 'Malawi');
INSERT INTO country (id, name) VALUES (114, 'Malaysia');
INSERT INTO country (id, name) VALUES (115, 'Mali');
INSERT INTO country (id, name) VALUES (116, 'Maldives');
INSERT INTO country (id, name) VALUES (117, 'Malta');
INSERT INTO country (id, name) VALUES (118, 'Martinique Island');
INSERT INTO country (id, name) VALUES (119, 'Mexico');
INSERT INTO country (id, name) VALUES (120, 'Mozambique');
INSERT INTO country (id, name) VALUES (121, 'Moldova');
INSERT INTO country (id, name) VALUES (122, 'Monaco');
INSERT INTO country (id, name) VALUES (123, 'Mongolia');
INSERT INTO country (id, name) VALUES (124, 'Morocco');
INSERT INTO country (id, name) VALUES (125, 'Myanmar (Burma)');
INSERT INTO country (id, name) VALUES (126, 'Maine Island');
INSERT INTO country (id, name) VALUES (127, 'Namibia');
INSERT INTO country (id, name) VALUES (128, 'Nauru');
INSERT INTO country (id, name) VALUES (129, 'Nepal');
INSERT INTO country (id, name) VALUES (130, 'Niger');
INSERT INTO country (id, name) VALUES (131, 'Nigeria');
INSERT INTO country (id, name) VALUES (132, 'The Netherlands (Holland)');
INSERT INTO country (id, name) VALUES (133, 'Nicaragua');
INSERT INTO country (id, name) VALUES (134, 'New Zealand');
INSERT INTO country (id, name) VALUES (135, 'New Caledonia Island');
INSERT INTO country (id, name) VALUES (136, 'Norway');
INSERT INTO country (id, name) VALUES (137, 'Norfolk Island');
INSERT INTO country (id, name) VALUES (138, 'O.A.E.');
INSERT INTO country (id, name) VALUES (139, 'Oman');
INSERT INTO country (id, name) VALUES (140, 'Pakistan');
INSERT INTO country (id, name) VALUES (141, 'Panama');
INSERT INTO country (id, name) VALUES (142, 'Papua New Guinea');
INSERT INTO country (id, name) VALUES (143, 'Paraguay');
INSERT INTO country (id, name) VALUES (144, 'Peru');
INSERT INTO country (id, name) VALUES (145, 'Pitcairn Island');
INSERT INTO country (id, name) VALUES (146, 'Poland');
INSERT INTO country (id, name) VALUES (147, 'Portugal');
INSERT INTO country (id, name) VALUES (148, 'Puerto Rico');
INSERT INTO country (id, name) VALUES (149, 'Reunion');
INSERT INTO country (id, name) VALUES (150, 'Rwanda');
INSERT INTO country (id, name) VALUES (151, 'Romania');
INSERT INTO country (id, name) VALUES (152, 'USA');
INSERT INTO country (id, name) VALUES (153, 'El Salvador');
INSERT INTO country (id, name) VALUES (154, 'Samoa');
INSERT INTO country (id, name) VALUES (155, 'San Marino');
INSERT INTO country (id, name) VALUES (156, 'Sao Tome and Principe');
INSERT INTO country (id, name) VALUES (157, 'Saudi Arabia');
INSERT INTO country (id, name) VALUES (158, 'Swaziland');
INSERT INTO country (id, name) VALUES (159, 'Saint Lucia');
INSERT INTO country (id, name) VALUES (160, 'Saint Helena Island');
INSERT INTO country (id, name) VALUES (161, 'North Korea');
INSERT INTO country (id, name) VALUES (162, 'Seychelles');
INSERT INTO country (id, name) VALUES (163, 'Saint Pierre and Miquelon');
INSERT INTO country (id, name) VALUES (164, 'Senegal');
INSERT INTO country (id, name) VALUES (165, 'Saint Kitts and Nevis');
INSERT INTO country (id, name) VALUES (166, 'Saint Vincent and the Grenadines');
INSERT INTO country (id, name) VALUES (167, 'Serbia');
INSERT INTO country (id, name) VALUES (168, 'Singapore');
INSERT INTO country (id, name) VALUES (169, 'Syria');
INSERT INTO country (id, name) VALUES (170, 'Slovakia');
INSERT INTO country (id, name) VALUES (171, 'Slovenia');
INSERT INTO country (id, name) VALUES (172, 'Solomon Islands');
INSERT INTO country (id, name) VALUES (173, 'Somalia');
INSERT INTO country (id, name) VALUES (174, 'Sudan');
INSERT INTO country (id, name) VALUES (175, 'Suriname');
INSERT INTO country (id, name) VALUES (176, 'Sierra Leone');
INSERT INTO country (id, name) VALUES (177, 'Tajikistan');
INSERT INTO country (id, name) VALUES (178, 'Taiwan');
INSERT INTO country (id, name) VALUES (179, 'Thailand');
INSERT INTO country (id, name) VALUES (180, 'Tanzania');
INSERT INTO country (id, name) VALUES (181, 'Togo');
INSERT INTO country (id, name) VALUES (182, 'Tokelau Islands');
INSERT INTO country (id, name) VALUES (183, 'Tonga');
INSERT INTO country (id, name) VALUES (184, 'Trinidad and Tobago');
INSERT INTO country (id, name) VALUES (185, 'Tuvalu');
INSERT INTO country (id, name) VALUES (186, 'Tunisia');
INSERT INTO country (id, name) VALUES (187, 'Turkmenistan');
INSERT INTO country (id, name) VALUES (188, 'Turks and Keikos');
INSERT INTO country (id, name) VALUES (189, 'Turkey');
INSERT INTO country (id, name) VALUES (190, 'Uganda');
INSERT INTO country (id, name) VALUES (191, 'Uzbekistan');
INSERT INTO country (id, name) VALUES (192, 'Uruguay');
INSERT INTO country (id, name) VALUES (193, 'Faroe Islands');
INSERT INTO country (id, name) VALUES (194, 'Fiji');
INSERT INTO country (id, name) VALUES (195, 'Philippines');
INSERT INTO country (id, name) VALUES (196, 'Finland');
INSERT INTO country (id, name) VALUES (197, 'France');
INSERT INTO country (id, name) VALUES (198, 'French Guinea');
INSERT INTO country (id, name) VALUES (199, 'French Polynesia');
INSERT INTO country (id, name) VALUES (200, 'Croatia');
INSERT INTO country (id, name) VALUES (201, 'Chad');
INSERT INTO country (id, name) VALUES (202, 'Montenegro');
INSERT INTO country (id, name) VALUES (203, 'Czech Republic');
INSERT INTO country (id, name) VALUES (204, 'Chile');
INSERT INTO country (id, name) VALUES (205, 'Switzerland');
INSERT INTO country (id, name) VALUES (206, 'Sweden');
INSERT INTO country (id, name) VALUES (207, 'Sri Lanka');
INSERT INTO country (id, name) VALUES (208, 'Ecuador');
INSERT INTO country (id, name) VALUES (209, 'Equatorial Guinea');
INSERT INTO country (id, name) VALUES (210, 'Eritrea');
INSERT INTO country (id, name) VALUES (211, 'Estonia');
INSERT INTO country (id, name) VALUES (212, 'Ethiopia');
INSERT INTO country (id, name) VALUES (213, 'South Africa');
INSERT INTO country (id, name) VALUES (214, 'South Korea');
INSERT INTO country (id, name) VALUES (215, 'South Ossetia');
INSERT INTO country (id, name) VALUES (216, 'Jamaica');
INSERT INTO country (id, name) VALUES (217, 'Japan');

